[connections.gsheets]
type = "service_account"
project_id = "censo-aislamientos"
private_key_id = "00d3b8964d5f058c13e0c3032b39cae9c83d5660"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9RYte96kniPUK
vmig9+OK08IBNSRn4CkSeFl6mPEV932ZQpfSioS4ocHLEdA9wGjLCPZOnaXwyA8y
Msovr2y0zOBBCRoe2+UAPBUI/nKgMWZ22p5X9EEKcalq/qqij7fc5KeLV3/j1xq8
kKVsPjGV8q/fDWpjaM3C2pX7TTkkLB45bAwFiCcjNsRevYmiOgtxyerl+umNo4BD
S7CjrqVMmQ+sEOTrw78MpubP32srYa91i2aM9weudod8LUEJpyhrRjkDugBv5cz/
qGZfUqM/pPBir3wtnpMbUFhOTG6RwEm/7WrRX/jVCb6LLtB6fjd1OjjZDCmxmLe/
BSRgsez3AgMBAAECggEAJaUuak4iE932txNWJiYH2PXzUWArhImeQbE0QuEmmnLm
RVRsdBDfAwYRUH2TiKS7cx6uNsa+WZzBAP//HOrsWS2isOzJiDe+XYSVvns1e004
Dw2+jsnjIdunkcNjVv/01veXp2xY4I1JIRY4AMaCAEwL1PaLIYiX3Fizmg8q/Vl8
38blikd6w1B7ujnRsRyXLXSJ2l5ux8gYLVvSNc/YjxgkNcjGQT1peTCiNHr0CWli
ien3tvkxC8qq/Bm9f+ASLpdfHJEv4ktgQ5OYIgIZNdnLXIDHu4CJUGD258tlhh+K
UxMhYKFrBJ7IcqZyv1J/bmCSi/novt09lvPRH1hHMQKBgQD3zGk2bt1Ypw1Joh4g
QQmRk/1iuHZjPwUIaOotsC+kUujJWB5ejCJHpFXeFnya8XL7fo2yEJKWttzPH6zY
2OCHEbVuiNmFIAjxLl4X4OdmdTmNnP5b+Qd0PQGW4mGquY0913krXv6PzJ6UUlaB
wx+TavAlA2y2kNEmdtyQdjDfeQKBgQDDiTzIuKSejJhr+UIvU6wAnJT8Tr3yiSqn
vqZqRYdm9s61uWesYCXcierhssi2VZiazQL5xmVECFG59OizQo7aaLdjZNDhDe2U
mxucGNbWblSAcQsM1d0ym5E/xEnfXmn9JZAlhwaLqA1EeLHdhOQ7qLh442GSQtCh
y3q6YvHj7wKBgGGR5jedraAznsLIh84xbaAZwmK1uT/Y15V5IgQ9ZHTyhGCLRuH5
kaHd7kWVWxjzS1AFg6uCZQXdGNKhaUC1HKtyaJsOXX/SnlLA7CHA17x7Gd9N2sXC
J5I4V0DfAI/lodyg1EAkll1ut141kYRknTFBoS8hyxOTsBbSJITpVNMZAoGAKwnU
+DUz/rXhgrqNZ89Z55SPcm1+f5jTa7KZ/IArSm1+mB8kA5vyGXW93km0xfVXLpN7
WTDi7zOJkY2nfnVi7g3od5ckJrUjGvd8/0G0X+RO8ypujTexhUcalFeHDwQ//fk7
nhb3SNwHd4+9To3Gkp8TY4Bg5ImSVFpuPAI1Tb8CgYEA8xFpLrsWdhGY3bsiWSAr
/8Np03pkCYTXlMaoYAQ0G4OTxTJlQjOhyTF41bpG2gb9UJYQXZ8pRZWGpLoylI7x
XqOc2ap25mspT2Rs5G85K2c7SdHSjjTtUZ2Fzhb8qe5stUXRVJjPw9V/gWB4eg+g
uL5i6HxUu65xaBiWopKw9ew=
-----END PRIVATE KEY-----
"""
client_email = "epidemio@censo-aislamientos.iam.gserviceaccount.com"
client_id = "110457809844102722127"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/epidemio%40censo-aislamientos.iam.gserviceaccount.com"
